### PR TITLE
Register new style

### LINKED ISSUE #980: docs bug - registering new styles
(Original issue 1276 created by jcorneli on 2016-08-16T18:46:51.178115+00:00)

I've written a new file icky.py as a variant of default.py in the styles directory but when I install pygments (`sudo python setup.py install`), I don't see the new "icky" style in the list of available styles (`./pygmentize -L styles`).

The documentation says that all I need to do is "drop it in the *styles* subpackage".  But that's somewhat unclear.  What's really needde is to add the style to `__init__.py`:

```
#!python
    ....
    'arduino':  'arduino::ArduinoStyle',
    'icky':  'icky::IckyStyle'
```
Perhaps you can add this to http://pygments.org/docs/styles/

### PR DESCRIPTION
**Pull request by flywire**
Closes #980

### CODE REVIEW

**Comment by Anteru** [comment]
Could you please add a test which exercises the new behavior?

**Comment by Anteru** [comment]
Ok so wait, `default_style` was _never_ used previously? I thought this would be an observable behavior change if someone relied on `default_style` but guess I was mistaken?

**Comment by birkenfeld** [comment]
Regarding this PR: I think the advice to copy stuff into the Pygments package should be removed wholesale, or at least clarified to only apply if you add a new style for submission as a PR.

**Comment by flywire** [comment]
Paste in a sample plugin here and I'll rewrite https://pygments.org/docs/plugins/ then tweak https://pygments.org/docs/styledevelopment/ to make it consistent with the comments above.

**Comment by flywire** [comment]
@birkenfeld [bd9eff0](https://github.com/pygments/pygments/pull/2183/commits/bd9eff03d182b5e4b20add2da22a866f019a07bf) only tries to represent the existing information more simply. The main need for it is the manual change to `__init__.py`. It would be easier if you just made any change you have in mind.

---

https://pygments.org/docs/  Hacking for Pygments is written around changing the Pygments package. I don't disagree it should be written around developing a Plugin but the section would need rewriting. It should start with https://pygments.org/docs/plugins/ containing a fully working `your` plugin consistent with the rest of the section. The emphasis of the other parts of this section should be reworked to be directed more towards the plugin than the package.

**Comment by flywire** [comment]
It's not documented in the existing guide but implied. The guide has example style code followed by _"That's it."_. It truly is _it_ if the file is placed into the style folder and the user doesn't need the services from registering the style (ie bringing up on a list of styles).

It's useful functionality so I wouldn't remove it but it is probably not worth any more documentation than a comment in the code.

**Comment by birkenfeld** [comment]
Hm, I don't like that either. It's also different from other components (lexers, formatters).

**Comment by Anteru** [comment]
What's the next step here? It feels like we can merge this change and then continue with the rest elsewhere?

**Comment by Anteru** [comment]
Merged, thanks. I'll add a warning note to the documentation to address @birkenfeld 's feedback. We still need a resolution for `get_style_by_name` though.

**Pull request merged**
