### PR TITLE
Add lexers.specials.OutputLexer.

### PR DESCRIPTION
**Pull request by doerwalter**
This pull request adds `lexers.specials.OutputLexer`, a lexer that highlights everything as `Token.Generic.Output` as discussed in issue #1835.

### CODE REVIEW

**Review by birkenfeld — APPROVED** [review]
LGTM.

**Comment by doerwalter** [comment]
We have this test failure:

```
               for mimetype in mimetypes:
  >               assert cls == lexers.get_lexer_for_mimetype(mimetype).__class__.__name__
  E               AssertionError: assert 'TextLexer' == 'OutputLexer'
  E                 - OutputLexer
  E                 + TextLexer
  ```
  
Removing the filename and MIME type configuration from from `OutputLexer` and `_mapping.py` fixes that.

I've updated the pull request.

**Comment by birkenfeld** [comment]
Perfect, thanks!

**Comment by Anteru** [comment]
Merged for the next release, thanks!

**Pull request merged**
