### PR TITLE
Add missing prompt color for Solarized style.

### PR DESCRIPTION
**Pull request by kdeldycke**
This might fix rendering on dark background as hinted by https://github.com/pygments/pygments/issues/1526.

### CODE REVIEW

**Comment by aroberge** [comment]
I think that the main `Generic` class should also have a color defined.

**Comment by Anteru** [comment]
I agree with @aroberge -- I presume this does work for tracebacks, but it wouldn't hurt to have `Generic` in there as well. Could you please add that while you're at it?

**Review by Anteru — CHANGES_REQUESTED** [review]
Plase add a color for `Generic` as well to have all bases covered. Otherwise looks good!

**Comment by kdeldycke** [comment]
Sorry @Anteru for the delay. Just added the `Generic` style in https://github.com/pygments/pygments/pull/1529/commits/d0ca1c8c66db7f5a16fc4f19085dc0fec3570141 .

This PR is ready to be merged! :)

**Review by kdeldycke — COMMENTED** [review]
Missing `Generic` has been added: https://github.com/pygments/pygments/pull/1529/commits/d0ca1c8c66db7f5a16fc4f19085dc0fec3570141

**Review by kdeldycke — COMMENTED** [review]
https://github.com/pygments/pygments/pull/1529/commits/d0ca1c8c66db7f5a16fc4f19085dc0fec3570141

**Comment by Anteru** [comment]
Merged, thanks!

**Pull request merged**
