### PR TITLE
svg formatter can now add configurable linenumbers

### PR DESCRIPTION
**Pull request by birkenfeld**
Ported from https://bitbucket.org/birkenfeld/pygments-main/pull-requests/582

### CODE REVIEW

**Comment by birkenfeld** [comment]
Hm, should line numbers be left or right aligned?

**Comment by Anteru** [comment]
They're left-aligned using this patch. I have a patch to make them right-aligned:

```patch
diff --git a/pygments/formatters/svg.py b/pygments/formatters/svg.py
index 58d4356d..fb75e494 100644
--- a/pygments/formatters/svg.py
+++ b/pygments/formatters/svg.py
@@ -141,8 +141,8 @@ class SvgFormatter(Formatter):
         
         if self.linenos:
             if counter % counter_step == 0:
-                outfile.write('<text x="%s" y="%s" %s>%s</text>' % (x,y,counter_style,counter))
-            line_x += self.linenowidth
+                outfile.write('<text x="%s" y="%s" %s text-anchor="end">%s</text>' % (x+self.linenowidth,y,counter_style,counter))
+            line_x += self.linenowidth + self.ystep
             counter += 1
 
         outfile.write('<text x="%s" y="%s" xml:space="preserve">' % (line_x, y))
@@ -159,7 +159,7 @@ class SvgFormatter(Formatter):
                 y += self.ystep
                 outfile.write('</text>\n')
                 if self.linenos and counter % counter_step == 0:
-                    outfile.write('<text x="%s" y="%s" %s>%s</text>' % (x,y,counter_style,counter))
+                    outfile.write('<text x="%s" y="%s" text-anchor="end" %s>%s</text>' % (x+self.linenowidth,y,counter_style,counter))
                 
                 counter += 1
                 outfile.write('<text x="%s" y="%s" ' 'xml:space="preserve">' % (line_x,y))
```
Right-aligned looks a bit better in my opinion. Happy to merge and apply the right-align patch if that looks good to you.

**Comment by birkenfeld** [comment]
Sounds good.

**Comment by Anteru** [comment]
Done!

**Comment by Anteru** [comment]
The history is a bit weird as I apparently have a `master` merge into the branch, but on master, everything should be fine I hope.

**Pull request merged**
