### PR TITLE
Post Style gallery fixes

### PR DESCRIPTION
**Pull request by not-my-profile**
Forgot to test it with `make dirhtml` (I was using `make html`).

### CODE REVIEW

**Comment by birkenfeld** [comment]
So it only works with one or the other? That is unfortunate...

**Comment by not-my-profile** [comment]
Yeah it is ... and I can't think of a good workaround.

* `make html` produces: `docs/styles.html` and `styles.html`, so `../styles.html` would be the right link
* `make dirhtml` produces `docs/styles/index.html` and `styles/index.html`, so `../../styles/` would be the right link

While for the other direction we can use the Sphinx `pathto` helper function, unless I am mistaken that isn't available from RST.

**Comment by birkenfeld** [comment]
The workaround is to add a file `doc/styles.rst` with only `:orphan:` as its content and to use :doc:`link text here </styles>`.

**Comment by not-my-profile** [comment]
Haha, right ... forgot that you are an expert on Sphinx^^ Now it's really fixed :)

**Comment by not-my-profile** [comment]
Added another commit that fixes the missing background color in the sidebar (unintended side-effect by the styles gallery commit).

I get that you tend to merge PRs by squashing all commits together ... I don't really like that^^ ... if commits do separate things I prefer to keep them separate ... makes for a more readable history.

**Comment by birkenfeld** [comment]
If you prefer that, no problem! Thanks for the attention to detail :)

**Comment by birkenfeld** [comment]
Argh, github defeated me...

**Comment by birkenfeld** [comment]
Ok, manually fetched and rebased master to your two commits.

**Comment by Anteru** [comment]
Thanks!

**Pull request merged**
