### PR TITLE
Added GDScript lexer

### PR DESCRIPTION
**Pull request by birkenfeld**
Ported from https://bitbucket.org/birkenfeld/pygments-main/pull-requests/732

### CODE REVIEW

**Comment by miskatonicstudio** [comment]
Hi! I was going to use Pygments for GDScript code blocks and realized that there is no lexer for GDScript yet. This PR seems to solve that problem, but it wasn't merged yet. Is there any reason other than the lack of tests that would prevent the merge? I can add the tests, if that will speed up the merging process.

**Comment by Anteru** [comment]
I didn't merge it because it does not pass the tests, so it's likely quite buggy. It would need to get fixed first to pass CI.

**Comment by miskatonicstudio** [comment]
@akien-mga have there been any significant changes in GDScript since this PR was introduced? If so, is there perhaps a new version of linter in a similar format, available in Godot repository and used for GDScript itself, that could be easily adapted for pygments?

**Comment by miskatonicstudio** [comment]
I've started working on the fixes in a separate branch and created a new PR: #1457 . It's WIP for now, I'll remove this status once I add proper tests for the lexer ;)

**Comment by akien-mga** [comment]
> @akien-mga have there been any significant changes in GDScript since this PR was introduced? If so, is there perhaps a new version of linter in a similar format, available in Godot repository and used for GDScript itself, that could be easily adapted for pygments?

Here's the current version of the GDScript lexer used for the Godot documentation: https://github.com/godotengine/godot-docs/blob/master/_extensions/gdscript.py

**Comment by miskatonicstudio** [comment]
> > @akien-mga have there been any significant changes in GDScript since this PR was introduced? If so, is there perhaps a new version of linter in a similar format, available in Godot repository and used for GDScript itself, that could be easily adapted for pygments?
> 
> Here's the current version of the GDScript lexer used for the Godot documentation: https://github.com/godotengine/godot-docs/blob/master/_extensions/gdscript.py

Thank you very much! It looks like I just need to copy this and add some tests, that is great news ;)

**Comment by Anteru** [comment]
Obsoleted by #1457

**Pull request closed without merging**
