### PR TITLE
Fixes for LilyPond

### PR DESCRIPTION
**Pull request by Jean-Abou-Samra**
See #1845.

@anteru

### CODE REVIEW

**Comment by Anteru** [comment]
Thanks, merged!

**Comment by Jean-Abou-Samra** [comment]
Hm, I don't see it in master -- does the "Changelog update" label mean something special?

**Comment by Anteru** [comment]
That means I need to add it to the changelog for the next release.

**Comment by Jean-Abou-Samra** [comment]
Ok, so it's not merged in the meantime? I'm just asking to understand, there is nothing urgent here.

**Comment by Anteru** [comment]
D'oh, pressed the wrong button :)

**Comment by Jean-Abou-Samra** [comment]
Ah, that explains it :-) Thanks!

**Pull request merged**
