### PR TITLE
Update javascript lexer

### PR DESCRIPTION
**Pull request by Mesteery**
Partially resolv*es* https://github.com/pygments/pygments/issues/1781.

### CODE REVIEW

**Comment by Anteru** [comment]
Merged, thanks! What's the rationale for removing `.tsx` as a Typescript alias?

**Comment by Mesteery** [comment]
> What's the rationale for removing .tsx as a Typescript alias?

Because this lexer doesn't really support TSX.

**Comment by vlakoff** [comment]
Using a variable named `from` in plain JavaScript code, I noticed it was highlighted as a reserved word (though it isn't a reserved word actually).

I pinpointed the cause to the following code, introduced by this PR:

https://github.com/pygments/pygments/blob/513f8fc34f7ec915994ac226ff333b2f6864b54c/pygments/lexers/javascript.py#L88-L89

**Comment by Mesteery** [comment]
`from` is an reserved word. By the way, when you use `'strict mode'`, your code will fail if you use `from` as a variable name.
`from` is used with `import` like `import something from 'package'`.

**Comment by vlakoff** [comment]
My code is in strict mode, and it is currently using a variable named `from`, which doesn't fail.

I think that's because `import`, then subsequently `from`, is reserved only if the script if interpreted as a module. See the [`import` documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import):

> In order to use the `import` declaration in a source file, the file must be interpreted by the runtime as a [module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). In HTML, this is done by adding `type="module"` to the [`<script>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) tag. Modules are automatically interpreted in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode).

Though, I don't think Pygments can distinguish between the "regular" and "module" types…

**Pull request merged**
