### PR TITLE
add missing keywords to JS and TS

### PR DESCRIPTION
**Pull request by Mesteery**
`from` keyword was missing (`import something from 'something'`)

### CODE REVIEW

**Comment by Anteru** [comment]
`from` is not a keyword though, is it? I was just trying to look up ES5/6 reserved words and from doesn't show up there (source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar). Is it only contextual?

And should `as` be also supported?

**Comment by Mesteery** [comment]
The `from` (and `as`) is used with ESM [imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)/[exports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export).

**Comment by Anteru** [comment]
I know, my point is though that from/as are not official keywords, or are they? I'm trying to understand if treating them the same as "import" is correct, given that is reserved. `as` seems to be missing in any case, could you please add that while you're at this?

**Comment by Mesteery** [comment]
> *Those that are always allowed as identifiers, but also appear as keywords within certain syntactic productions, at places where Identifier is not allowed: **`as`**, `async`, **`from`**, `get`, `of`, `set`, and `target`.*

https://tc39.es/ecma262/2020/#sec-keywords-and-reserved-words

**Comment by Mesteery** [comment]
For a more general PR, we could add :
  * [ ] more errors (`Error`, `EvalError`, `InternalError`, `RangeError`, `ReferenceError`, `SyntaxError`, `TypeError`, `URIError`) as `Name.Exception` ?
  * [ ] the `global` object (`Name.Builtin`, Node.js)
  * [ ] more `Name.Builtin` (such as typed arrays, `Intl`, `DataView`, `Set`, `Map`, `WeakSet`, `WeakMap`, `Reflect`, `JSON`, `ArrayBuffer`) ?

**Comment by Anteru** [comment]
Yes, that sounds good, but I'd rather do it in a separate PR. This here is nice and self-contained. Can you please un-draft it so I can merge it, then file another PR for the other changes?

**Pull request merged**
