### PR TITLE
Add Sieve lexer

### PR DESCRIPTION
**Pull request by sblondon**
This PR adds a Sieve lexer.
Sieve is a language to filter incoming e-mails into the user mailbox.

### CODE REVIEW

**Comment by Anteru** [comment]
Thanks for your contribution -- looks like it's causing some test failures though. Could you please take a look at them? If you need any help, please let me know!

**Comment by sblondon** [comment]
@Anteru I made some improvements but it still does not pass the test. I don't understand why because running:
`./pygmentize -v -O full tests/examplefiles/example.sieve`
works properly.

I get the same error like Github CI when I run `tox`:
```
E           AssertionError: lexer <pygments.lexers.SieveLexer> generated error token for /home/stephane/src/pygments/tests/examplefiles/example.sieve: '.' at position 1109
E           assert Token.Error != Token.Error
```

The tests are green if the file `./tests/examplefiles/example.sieve` is empty.
If `example.sieve` contains only:
```
require
```
I get another error, perhaps it's an hint about the issue:
```
[...]
>               assert False, absfn
E               AssertionError: /home/stephane/src/pygments/tests/examplefiles/example.sieve
E               assert False

tests/test_examplefiles.py:141: AssertionError
---------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------
--- 

+++ 

@@ -1 +1 @@

-[(Token.Punctuation, '\n')]
+[(Token.Keyword.Namespace, 'require'), (Token.Punctuation, '\n')]
```

Do you have any idea?

**Comment by sblondon** [comment]
After `rm -rf tests/examplefiles/output`, the error generated by `example.sieve` file disappears.

There are two errors in python3.7  with `example.praat` and `example.rkt` files which are equivalent (missing token). For `example.praat`:
```
- (Token.Name, '#%A|||b #true C\n\\|ｄ\u2002'),
- (Token.Text, ''),
+ (Token.Name, '#%A|||b #true C\n\\|ｄ'),
+ (Token.Text, ''),
+ (Token.Text, '\u2002'),
```
These errors are also in `master` branch of `pygments`.

**Comment by birkenfeld** [comment]
You saw the failure generated by cached output in `tests/examplefiles/output` because a special test mode was active which shouldn't be in the normal case, I've fixed that in d338695666a8255ec1dd188a2fa653fc42516aa3.

This shouldn't matter for GitHub CI since it always starts with a clean checkout.

Running the tests locally with your branch, I now get the following error:
```
E           AssertionError: lexer <pygments.lexers.SieveLexer> generated error token for /home/gbr/devel/pygments/tests/examplefiles/example.sieve: '.' at position 1109
```
which also occurs on the CI.

**Comment by sblondon** [comment]
@birkenfeld Thanks for your help! I rebased the branch and I get the same error too. I will investigate it.

I wonder if `make clean` should remove the `tests/examplefiles/output/` directory. I can do it in another PR.

**Comment by birkenfeld** [comment]
> I wonder if `make clean` should remove the `tests/examplefiles/output/` directory. I can do it in another PR.

Yes, that's a good idea in any case.

**Comment by sblondon** [comment]
I fixed the test. `$` was not understood as end-of-line in regular expression in 'text' block so I replaced it by `\n`.

**Pull request merged**
