### PR TITLE
:pencil2: : Added much more python versions

### PR DESCRIPTION
**Pull request by ThatXliner**
Your original workflow only covered a tiny amount of python versions. My proposal is to cover *all* the versions you support, including the minor versions. It may seem like a waste of time, but it does give people more confidence.

### CODE REVIEW

**Comment by Anteru** [comment]
@birkenfeld That seems like serious overkill to me -- what do you think?

**Comment by ThatXliner** [comment]
Hmm, maybe.

**Comment by birkenfeld** [comment]
No, sorry, latest of each minor is fine.  We don't need the additional work to keep track of each patch version, and neither the false-negatives, see Windows on 3.6.12 in this run.

**Comment by ThatXliner** [comment]
👌

**Pull request closed without merging**
