### PR TITLE
Add lexer for PRQL

### PR DESCRIPTION
**Pull request by vanillajonathan**
Adds a lexer for the PRQL query language.

PRQL is a modern language for transforming data — a simple, powerful, pipelined SQL replacement.
https://prql-lang.org/
https://github.com/PRQL/prql

### CODE REVIEW

**Comment by Anteru** [comment]
Hello! This needs a test file before we can continue, look at [the lexer development](https://pygments.org/docs/contributing/) page.

**Comment by Anteru** [comment]
Thanks for updating the _mapping file etc., but please do add an example file as well under `/examplefiles`.

**Comment by Anteru** [comment]
Thanks for the updates! Before we do burn down a forest here running CI, can you make sure to run the checks locally? Is there anything preventing you from using `tox`? I need to manually approve the CI run, and it's fairly simple stuff to fix that can be all checked locally.

**Comment by vanillajonathan** [comment]
I can use `tox` but I am a bit new to this, I hadn't used it before.

**Comment by Anteru** [comment]
`pip install tox` (in the virtual environment you use for development) and then `tox`, `tox -e check`, and possibly `tox -e mapfiles` (to regenerate them)

**Comment by Anteru** [comment]
`prql.py` is missing the correct copyright info. It has to be 2006-2023, not just 2023.

**Comment by vanillajonathan** [comment]
@Anteru I've updated the copyright into.

**Review by Anteru — APPROVED** [review]

**Comment by Anteru** [comment]
Merged, thanks!

**Pull request merged**
