### PR TITLE
Make default style meet WCAG AA

### PR DESCRIPTION
**Pull request by not-my-profile**
Accessibility by default is important.

The colors with a too low contrast were adjusted just
so much that they match the required contrast of 4.5.

Part of #1718.

---

`tests/html_linenos_expected_output` somehow needs to be updated for the tests to pass ... but I don't know how.

## Screenshots

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

Before:

image

After:

image

### CODE REVIEW

**Comment by Anteru** [comment]
Thanks for preparing this! I'll fix the lineos update. Do you happen to have a before/after screenshot for the default style?

**Comment by not-my-profile** [comment]
Yeah, I added screenshots for all changed colors.

**Comment by Anteru** [comment]
Thanks a lot. That is much more subtle than I expected.

**Comment by birkenfeld** [comment]
Indeed, thanks a lot!

**Comment by not-my-profile** [comment]
You're welcome :) Once this is merged, I'll proceed with the steps I outlined in #1718.

**Comment by Anteru** [comment]
Merged, thanks a lot. Pray continue.

**Pull request merged**
