### PR TITLE
Replace pyflakes with Ruff

### PR DESCRIPTION
**Pull request by jeanas**
- Fix/ignore Ruff lints
- Replace pyflakes with Ruff in `tox -e check`

### CODE REVIEW

**Comment by birkenfeld** [comment]
You're on a roll! Looks good.

**Comment by Anteru** [comment]
I was going to say, taking a week off or something :) Thanks, looks good. Makes me look really bad here though :(

**Comment by Anteru** [comment]
This is weird. When I run `ruff check .`, I get 1301 errors, unless I use `ruff check --ignore E501 .`. Why does `tox` not complain? It supposedly runs `ruff check .` unless I'm missing something?

**Comment by birkenfeld** [comment]
> I was going to say, taking a week off or something :) Thanks, looks good. Makes me look really bad here though :(

How does it make it you look bad? This is not a competition :)

**Pull request merged**
