### PR TITLE
Add a lexer for Schemas for Minecraft Add-ons and 4 examples

### PR DESCRIPTION
**Pull request by MiemieMethod**
**Schema** is a formal language for the game Minecraft official staff and docs to show data file structures and interface formats, and also for Minecraft Add-ons creators to communicate or teach with each other. 

Reference: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/schemasreference/
Community usage example: https://www.mcbe-dev.net/addons/data-driven/manifest.html

This lexer is summarized from official and some community examples for maximum coverage.

Four examples are provided for lexer tests.

### CODE REVIEW

**Comment by Anteru** [comment]
Quick look: Please run `pytest --update-goldens` to add golden test output, and I think the name is a tad too generic, can you please rename the lexer to `MinecraftSchemaLexer` or something because I doubt that this is the only language ever that will claim the `schema` name.

**Comment by birkenfeld** [comment]
Please make it clear that this is Minecraft related, i.e. call the file minecraft.py, the lexer name 'Minecraft Schema', the alias 'minecraft-schema', the class 'MinecraftSchemaLexer' etc.

**Comment by birkenfeld** [comment]
Oops, I duplicated @Anteru 's request, never mind.

**Comment by MiemieMethod** [comment]
> Please make it clear that this is Minecraft related, i.e. call the file minecraft.py, the lexer name 'Minecraft Schema', the alias 'minecraft-schema', the class 'MinecraftSchemaLexer' etc.

Thanks for your suggestion, but I see that there exist `MCFunctionLexer` and `SNBTLexer` in `mcfunction.py`. Is it better to merge them into one file and name it `minecraft.py`, or just like my changes - simply renaming Schema to MCSchema?

**Comment by Anteru** [comment]
I'd prefer all Minecraft-related lexers to move into a single `minecraft.py` file. You can create a separate PR for that if you want or keep it in this PR if that's easier for you.

**Comment by MiemieMethod** [comment]
> I'd prefer all Minecraft-related lexers to move into a single `minecraft.py` file. You can create a separate PR for that if you want or keep it in this PR if that's easier for you.

Thanks, I'll repull a request for that. Btw, I see the git action failed but have some difficulty understanding the reason. If you were convenient to have a look?

**Pull request closed without merging**
