### PR TITLE
Misc. SchemeLexer improvements

### PR DESCRIPTION
**Pull request by Jean-Abou-Samra**
- Highlight string escapes,
- Recognize fancy numbers (e.g. fractions and infinities),
- Autogenerate builtins (using the Guile implementation),
- Support simple datums commented with `#;`,
- Recognize `#:keywords`.

(For history readability, it would be ideal if the commits were merged without squashing.)

### CODE REVIEW

**Comment by birkenfeld** [comment]
LGTM in general. Can the small test file be moved to `snippets`?

**Comment by Jean-Abou-Samra** [comment]
Done.

**Comment by birkenfeld** [comment]
No, LGTM, sorry for dropping the ball. Thanks for the PR!

**Comment by Jean-Abou-Samra** [comment]
Thank you!

**Pull request merged**
