### PR TITLE
Added dracula theme style

### PR DESCRIPTION
**Pull request by danvilar**
Related to issue #1631

### CODE REVIEW

**Comment by danvilar** [comment]
I need some help with the failed check

**Comment by Leistungsabfall** [comment]
Try force pushing your last commit

**Comment by danvilar** [comment]
> Try force pushing your last commit

I'm not sure how to do it. I did `git push --force` on my fork, but it just says "Everything up-to-date". I apologise in advance, I'm not used to doing it.

**Comment by Leistungsabfall** [comment]
Run `git commit --amend` and then close nano (or whatever your default text editor is) without saving. Then execute `git push --force`.

**Comment by danvilar** [comment]
Thank you @Leistungsabfall! I never used amends before. Nice to know for the future!

**Comment by Leistungsabfall** [comment]
You're welcome :santa:

**Comment by Anteru** [comment]
Merged for the next release, thanks!

**Comment by AkibAzmain** [comment]
@Anteru Can you please review my pull request #1642?

**Comment by Anteru** [comment]
I just noticed while preparing the 2.7.4 release that the license terms don't match. I've reverted the change; can you please check again and commit it with the correct license? I presume this was all written by you and is original code, so it shouldn't be a problem. According to our Contributing guidelines, you must accept putting the code under 2-clause BSD.

**Comment by tomy0000000** [comment]
@danvilar Just in case you missed this, been waiting for this, please take a look. Thanks.

**Comment by danvilar** [comment]
I will make a new pull request as soon as possible.

**Pull request merged**
