### PR TITLE
Supports single quote strings in AutoItLexer

### PR DESCRIPTION
**Pull request by trdean1**
Fix for issue #1663

### CODE REVIEW

**Comment by Anteru** [comment]
Can you please add a test for it?

**Comment by trdean1** [comment]
Done - I have added a line to `tests/examplefiles/autoit/autoit_submit.au3` that tests this case and updated the corresponding output file after verifying the output from pytest was correct.

**Comment by Anteru** [comment]
Thanks. Something doesn't look right though: The `'` appears both as `Token.String`, and then again with the rest of the string. That doesn't seem quite right to me, as you'd get `''boo; bar; "baz"''` when you paste them back together. Can you please double check that the output looks correct?

**Comment by trdean1** [comment]
I think it looks correct to me. The `'`'s on line 177 of `autoit_submit.au3.output` are just displaying the token as a string.  Compare to lines 14-16 which holds the output of `"http://localhost:8080"`.  This becomes
```
'"'   Literal.String
'http://localhost:8080'  Literal.String
'"'   Literal.String
```

**Comment by Anteru** [comment]
Ah, you're right, my bad! Thanks, merged for the next release!

**Pull request merged**
