### PR TITLE
add coffee theme

### PR DESCRIPTION
**Pull request by TruncatedDinoSour**
adds [coffee theme](https://github.com/coffee-theme/coffee/), based on its vim theme

image

### CODE REVIEW

**Comment by TruncatedDinoSour** [comment]
preview https://us.ari.lt/blog/@ari/syntax-highlighting-test ( the whole subdomain is in testing rn but if u want smt tht works ( at least atm ) use tht )

**Comment by TruncatedDinoSour** [comment]
:3

**Comment by jeanas** [comment]
Sorry for the delay, there are many PRs on this repo and this is a dense period for many people. I'll try to review it before the end of the week, unless another maintainer does it before me.

**Comment by TruncatedDinoSour** [comment]
> Sorry for the delay, there are many PRs on this repo and this is a dense period for many people. I'll try to review it before the end of the week, unless another maintainer does it before me.

no worries, take ur time <3

**Comment by jeanas** [comment]
This looks OK. Merged, thank you. (The style has a relatively low contrast, but since it's already used elsewhere, I guess you want consistency. Note that on our [styles page](https://pygments.org/styles/), it will appear among the “Styles with a lower contrast”.)

**Comment by TruncatedDinoSour** [comment]
> This looks OK. Merged, thank you. (The style has a relatively low contrast, but since it's already used elsewhere, I guess you want consistency. Note that on our [styles page](https://pygments.org/styles/), it will appear among the “Styles with a lower contrast”.)

thanks

and yeah, the consistency is important to me, i could possibly contribute a high contrast version in the future :)

**Pull request merged**
