### PR TITLE
Overhaul demo and support running it locally

### LINKED ISSUE #2137: Demo not working on website
Hey

Trying to highlight some code on the demo page - https://pygments.org/demo/ - but it doesn't work. The highlight loader is just spinning the whole time.

There is an error in the console - 
Screenshot 2022-05-12 at 15 08 20

### PR DESCRIPTION
**Pull request by amitkummer**
Hi @birkenfeld, @Jean-Abou-Samra, @Anteru, while trying to fix #2137, I noticed the demo page in the docs does not run locally, as it requires building and serving Pyodide.

I managed to fix this and run the demo locally by creating a `make` target for building Pyodide using Docker, and tweaking the documentation's build command to use it.
Along the way I upgraded Pyodide from `v0.16` to `v0.20`, removed deprecated code, and fixed a couple of issues in the demo's JavaScript (this includes #2137).

Overview of changes made:

- Add a `make` target to the documentation's Makefile for making a Pyodide build  with Pygments from the current checkout, using Docker. Additionally, use this target when building the demo.
- Add instructions on how to run the docs with the demo locally to the README.
- Update the demo to work with Pyodide `v0.20` (some stuff have been deprecated).
- Fix #2137 and also another small issue in the demo's JavaScript.
- Remove the old GitHub action for building Pyodide in the CI, as it is now obsolete.
- Upgrade version of the action used for deploying to GitHub pages. 

I've tested these changes locally and also successfully deployed them to: https://amitkummer.github.io/demo/

### CODE REVIEW

**Comment by Jean-Abou-Samra** [comment]
Nice! I'm not knowledgeable about this part, so I'll leave the more detailed review to @birkenfeld and @Anteru, but I want to thank you for preparing this.

**Comment by birkenfeld** [comment]
This looks excellent, thanks a lot! I'll give it a try tomorrow but I really look forward to getting rid of the current half-baked solution.

**Comment by birkenfeld** [comment]
Hm, build fails for me locally:
```
 > [build-stage 5/5] RUN make:                                                                                                                                                                                                                                                                                              
#9 0.237 ./tools/dependency-check.sh                                                                                                                                                                                                                                                                                        
#9 0.683 emcc -o src/core/docstring.o -c src/core/docstring.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/                                                                                                                                                                                                                             
#9 0.941 emcc -o src/core/error_handling.o -c src/core/error_handling.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 1.194 emcc -o src/core/hiwire.o -c src/core/hiwire.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 1.443 emcc -o src/core/js2python.o -c src/core/js2python.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 1.690 emcc -o src/core/jsproxy.o -c src/core/jsproxy.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 1.934 src/core/jsproxy.c:1396:1: warning: unused label 'finally' [-Wunused-label]
#9 1.934 finally:
#9 1.934 ^~~~~~~~
#9 1.934 1 warning generated.
#9 1.942 emcc -o src/core/main.o -c src/core/main.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 2.210 emcc -o src/core/pyproxy.o -c src/core/pyproxy.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 2.462 src/core/pyproxy.c:221:8: warning: variable 'success' set but not used [-Wunused-but-set-variable]
#9 2.462   bool success = false;
#9 2.462        ^
#9 2.462 src/core/pyproxy.c:897:1: warning: unused label 'finally' [-Wunused-label]
#9 2.462 finally:
#9 2.462 ^~~~~~~~
#9 2.462 2 warnings generated.
#9 2.467 emcc -o src/core/python2js_buffer.o -c src/core/python2js_buffer.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 2.722 emcc -o src/core/python2js.o -c src/core/python2js.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -Isrc/core/
#9 2.978 date +"[%F %T] Building pyodide.asm.js..."
#9 3.213 [2022-05-21 05:27:11] Building pyodide.asm.js...
#9 3.213 [ -d build ] || mkdir build
#9 3.416 em++ -o build/pyodide.asm.js src/core/docstring.o src/core/error_handling.o src/core/error_handling_cpp.o src/core/hiwire.o src/core/js2python.o src/core/jsproxy.o src/core/main.o src/core/pyproxy.o src/core/python2js_buffer.o src/core/python2js.o \
#9 3.416        -O2 -g0 -s MODULARIZE=1 -s LINKABLE=1 -s EXPORT_ALL=1 -s WASM=1 -std=c++14 -s LZ4=1 -L /src/pyodide/cpython/installs/python-3.10.2/lib/  -s MAIN_MODULE=1 -s EXPORT_NAME="'_createPyodideModule'" -s EXPORTED_FUNCTIONS='["___cxa_guard_acquire", "__ZNSt3__28ios_base4initEPv", "_main"]' -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] -s DEMANGLE_SUPPORT=1 -s USE_FREETYPE=1 -s USE_LIBPNG=1 -s FORCE_FILESYSTEM=1 -s TOTAL_MEMORY=20971520 -s ALLOW_MEMORY_GROWTH=1 -lpython3.10 -lffi -lsqlite3 -lbz2 -lstdc++ -lidbfs.js -lnodefs.js -lproxyfs.js -lworkerfs.js --use-preload-plugins --preload-file /src/pyodide/cpython/installs/python-3.10.2/lib/python3.10@/lib/python3.10 --preload-file src/py/lib@/lib/python3.10/ --exclude-file "*__pycache__*" --exclude-file "*/test/*" --exclude-file "*/tests/*" --exclude-file "*/distutils/*" --pre-js src/core/pre.js
#9 6.039 converting to ArrayBuffer
#9 6.042 compressing package of size 10083842
#9 6.147 compressed package into 5398736
#9 6.151 compressed in 110 ms
#9 15.53 sed -i -E 's/var __Z[^;]*;//g' build/pyodide.asm.js
#9 15.84 sed -i '1i\
#9 15.84        "use strict";\
#9 15.84        let setImmediate = globalThis.setImmediate;\
#9 15.84        let clearImmediate = globalThis.clearImmediate;\
#9 15.84        let baseName, fpcGOT, dyncallGOT, fpVal, dcVal;\
#9 15.84 ' build/pyodide.asm.js
#9 16.05 # Remove last 6 lines of pyodide.asm.js, see issue #2282
#9 16.25 # Hopefully we will remove this after emscripten fixes it, upstream issue
#9 16.45 # emscripten-core/emscripten#16518
#9 16.66 # Sed nonsense from https://stackoverflow.com/a/13383331
#9 16.86 sed -i -n -e :a -e '1,6!{P;N;D;};N;ba' build/pyodide.asm.js
#9 17.07 echo "globalThis._createPyodideModule = _createPyodideModule;" >> build/pyodide.asm.js
#9 17.27 date +"[%F %T] done building pyodide.asm.js."
#9 17.47 [2022-05-21 05:27:25] done building pyodide.asm.js.
#9 17.47 # We can't input pyproxy.js directly because CC will be unhappy about the file
#9 17.71 # extension. Instead cat it and have CC read from stdin.
#9 17.91 # -E : Only apply prepreocessor
#9 18.11 # -C : Leave comments alone (this allows them to be preserved in typescript
#9 18.32 #      definition files, rollup will strip them out)
#9 18.52 # -P : Don't put in macro debug info
#9 18.73 # -imacros pyproxy.c : include all of the macros definitions from pyproxy.c
#9 18.93 #
#9 19.13 # First we use sed to delete the segments of the file between
#9 19.33 # "// pyodide-skip" and "// end-pyodide-skip". This allows us to give
#9 19.53 # typescript type declarations for the macros which we need for intellisense
#9 19.74 # and documentation generation. The result of processing the type
#9 19.94 # declarations with the macro processor is a type error, so we snip them
#9 20.14 # out.
#9 20.34 rm -f src/js/pyproxy.gen.ts
#9 20.55 echo "// This file is generated by applying the C preprocessor to core/pyproxy.ts" >> src/js/pyproxy.gen.ts
#9 20.75 echo "// It uses the macros defined in core/pyproxy.c" >> src/js/pyproxy.gen.ts
#9 20.95 echo "// Do not edit it directly!" >> src/js/pyproxy.gen.ts
#9 21.15 cat src/core/pyproxy.ts | \
#9 21.15        sed '/^\/\/\s*pyodide-skip/,/^\/\/\s*end-pyodide-skip/d' | \
#9 21.15        emcc -E -C -P -imacros src/core/pyproxy.c -O2 -g0 -fPIC  -Wall -Wno-warn-absolute-paths -Werror=unused-variable -Werror=sometimes-uninitialized -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=unused-result -I/src/pyodide/cpython/installs/python-3.10.2/include/python3.10 -s EXCEPTION_CATCHING_ALLOWED=['we only want to allow exception handling in side modules'] - \
#9 21.15        >> src/js/pyproxy.gen.ts
#9 21.49 npx rollup -c src/js/rollup.config.js
#9 22.44 
#9 22.44 ./src/js/pyodide.ts → build//pyodide.mjs...
#9 26.73 created build//pyodide.mjs in 4.2s
#9 26.73 
#9 26.73 ./src/js/pyodide.umd.ts → build//pyodide.js...
#9 29.82 created build//pyodide.js in 3s
#9 29.85 cp src/templates/console.html build/console.html
#9 30.09 sed -i -e 's#{{ PYODIDE_BASE_URL }}#./#g' build/console.html
#9 30.29 cd /src/pyodide/cpython/installs/python-3.10.2/lib/python3.10 && tar --exclude=__pycache__ -cf /src/pyodide/build/distutils.tar distutils
#9 30.53 date +"[%F %T] Building packages..."
#9 30.77 [2022-05-21 05:27:38] Building packages...
#9 30.77 make -C packages
#9 30.98 make[1]: Entering directory '/src/pyodide/packages'
#9 31.64 /usr/local/bin/python3.10 -m pip install --prefix=/root/.local -e ../pyodide-build
#9 32.56 Obtaining file:///src/pyodide/pyodide-build
#9 32.65   Installing build dependencies: started
#9 36.06   Installing build dependencies: finished with status 'done'
#9 36.07   Getting requirements to build wheel: started
#9 37.09   Getting requirements to build wheel: finished with status 'done'
#9 37.09     Preparing wheel metadata: started
#9 38.18     Preparing wheel metadata: finished with status 'done'
#9 38.19 Requirement already satisfied: ruamel.yaml in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (0.17.21)
#9 38.19 Requirement already satisfied: cython<3.0 in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (0.29.28)
#9 38.20 Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (6.0)
#9 38.20 Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (21.3)
#9 38.20 Requirement already satisfied: build==0.7.0 in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (0.7.0)
#9 38.20 Requirement already satisfied: tomli in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (2.0.1)
#9 38.20 Requirement already satisfied: wheel in /usr/local/lib/python3.10/site-packages (from pyodide-build==0.20.0.dev0) (0.37.1)
#9 38.23 Requirement already satisfied: pep517>=0.9.1 in /usr/local/lib/python3.10/site-packages (from build==0.7.0->pyodide-build==0.20.0.dev0) (0.12.0)
#9 38.23 Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.10/site-packages (from packaging->pyodide-build==0.20.0.dev0) (3.0.7)
#9 38.25 Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /usr/local/lib/python3.10/site-packages (from ruamel.yaml->pyodide-build==0.20.0.dev0) (0.2.6)
#9 38.59 Installing collected packages: pyodide-build
#9 38.59   Attempting uninstall: pyodide-build
#9 38.59     Found existing installation: pyodide-build 0.20.0.dev0
#9 38.60     Uninstalling pyodide-build-0.20.0.dev0:
#9 38.60       Successfully uninstalled pyodide-build-0.20.0.dev0
#9 38.61   Running setup.py develop for pyodide-build
#9 40.05 Successfully installed pyodide-build
#9 40.05 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#9 40.07 WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
#9 40.07 You should consider upgrading via the '/usr/local/bin/python3.10 -m pip install --upgrade pip' command.
#9 40.14 mkdir -p /src/pyodide/packages/.artifacts
#9 40.78 PYODIDE_ROOT=/src/pyodide python -m pyodide_build buildall . /src/pyodide/build \
#9 40.78 --only "Pygments" --n-jobs ${PYODIDE_JOBS:-4} \
#9 40.78 --log-dir=./build-logs
#9 42.54 The following packages are already built: distutils, micropip, packaging, pyparsing, and test
#9 42.54 
#9 42.54 Building the following packages: Pygments
#9 42.54 [1/1] (thread 1) building Pygments
#9 42.54 Error building Pygments. Printing build logs.
#9 42.54 Traceback (most recent call last):
#9 42.54   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
#9 42.54     return _run_code(code, main_globals, None,
#9 42.54   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
#9 42.54     exec(code, run_globals)
#9 42.54   File "/src/pyodide/pyodide-build/pyodide_build/__main__.py", line 64, in <module>
#9 42.54     main()
#9 42.54   File "/src/pyodide/pyodide-build/pyodide_build/__main__.py", line 58, in main
#9 42.54     args.func(args)
#9 42.54   File "/src/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 868, in main
#9 42.54     build_package(
#9 42.54   File "/src/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 736, in build_package
#9 42.54     prepare_source(pkg_root, build_dir, srcpath, source_metadata)
#9 42.54   File "/src/pyodide/pyodide-build/pyodide_build/buildpkg.py", line 308, in prepare_source
#9 42.54     shutil.copytree(srcdir, srcpath)
#9 42.54   File "/usr/local/lib/python3.10/shutil.py", line 556, in copytree
#9 42.54     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
#9 42.54   File "/usr/local/lib/python3.10/shutil.py", line 512, in _copytree
#9 42.54     raise Error(errors)
#9 42.54 shutil.Error: [('/pygments/.tox/pypy3/bin/python', '/src/pyodide/packages/Pygments/build/Pygments-2.99/.tox/pypy3/bin/python', "[Errno 2] No such file or directory: '/pygments/.tox/pypy3/bin/python'"), ('/pygments/.tox/pypy3/bin/python3', '/src/pyodide/packages/Pygments/build/Pygments-2.99/.tox/pypy3/bin/python3', "[Errno 2] No such file or directory: '/pygments/.tox/pypy3/bin/python3'"), ('/pygments/.tox/pypy3/bin/pypy3', '/src/pyodide/packages/Pygments/build/Pygments-2.99/.tox/pypy3/bin/pypy3', "[Errno 2] No such file or directory: '/pygments/.tox/pypy3/bin/pypy3'"), ('/pygments/.tox/pypy3/bin/pypy', '/src/pyodide/packages/Pygments/build/Pygments-2.99/.tox/pypy3/bin/pypy', "[Errno 2] No such file or directory: '/pygments/.tox/pypy3/bin/pypy'"), ('/pygments/.tox/pypy3/bin/python3.6', '/src/pyodide/packages/Pygments/build/Pygments-2.99/.tox/pypy3/bin/python3.6', "[Errno 2] No such file or directory: '/pygments/.tox/pypy3/bin/python3.6'")]
#9 42.54 [2022-05-21 05:27:49] Building package Pygments...
#9 42.54 [2022-05-21 05:27:50] Failed building package Pygments in 0.6 seconds.
#9 42.54 ERROR: cancelling buildall
#9 42.54 [1/1] (thread 1) failed Pygments in 0.80 s
#9 42.56 make[1]: *** [Makefile:13: all] Error 1
#9 42.56 make[1]: Leaving directory '/src/pyodide/packages'
#9 42.56 make: *** [Makefile:225: build/packages.json] Error 2
```

**Comment by birkenfeld** [comment]
Also, that is a hefty Docker image. I hope it is cached on github actions?

**Comment by birkenfeld** [comment]
Ok, after looking a little more closely at the errors, I removed `.tox` from my checkout and got another error ("Exception: Unexpected number of wheels 13 when building Pygments"). Then I removed all git-ignored stuff and it built fine *shrug*.

The result doesn't work on `file:///` but I guess that's to be expected.

With a local HTTP server where the output isn't in the root, the absolute paths in `demo.js` and `demo-worker.js` fail, but that is already the case before this PR and can be fixed later if wanted.

**Comment by amitkummer** [comment]
Thanks for the timely review @birkenfeld, I think I've addressed your comments.

> Also, that is a hefty Docker image. I hope it is cached on github actions?

Unfortunately, no.


> Ok, after looking a little more closely at the errors, I removed .tox from my checkout and got another error ("Exception: Unexpected number of wheels 13 when building Pygments"). Then I removed all git-ignored stuff and it built fine shrug.

I managed to reproduce the error you got. I fixed it by adding all files which are ignored by git to `.dockerignore`, so they are not present during the build process.


> The result doesn't work on file:/// but I guess that's to be expected.

Yes. 


> With a local HTTP server where the output isn't in the root, the absolute paths in demo.js and demo-worker.js fail, but that is already the case before this PR and can be fixed later if wanted.

Nice catch, fixed this by changing the problematic paths to be relative.


Additionally, I noticed I should have marked the new `pyodide` make target as phony, so I fixed that. In the process, I also renamed the new `_pyodide` directory to `pyodide`, as the leading underscore was there to avoid clashing with the name of the `make` target.

**Comment by amitkummer** [comment]
> With a local HTTP server where the output isn't in the root, the absolute paths in demo.js and demo-worker.js fail, but that is already the case before this PR and can be fixed later if wanted.

Nevermind, my fix for this was not working, and I am discarding the change.

**Comment by birkenfeld** [comment]
Yeah it depends on if building html or dirhtml, unfortunately, and `pathto` is not available in templated static files.

**Pull request merged**
