### PR TITLE
a filter for math symbols

### PR DESCRIPTION
**Pull request by lsf37**
This filer replaces math symbols from e.g. LaTeX and Isabelle with
corresponding unicode. It could be expanded to other math-heavy
languages.

(Ported from an existing bitbucket PR)

### CODE REVIEW

**Comment by lsf37** [comment]
Oops, failing tests. I guess things have moved on from then, will look into it.

**Comment by lsf37** [comment]
Ok, fixed.

**Comment by Anteru** [comment]
Can you please add a unit test for this, just to make sure there is some code calling it running during CI/CD?

**Comment by lsf37** [comment]
Sure, will probably have a look tomorrow.

**Comment by lsf37** [comment]
Rebased and test added. I wasn't quite sure where exactly it should go. It's now together with the other filter tests, which seemed appropriate.

**Comment by Anteru** [comment]
Yep, that seems fine. I want to make sure that CI is covering this. Thanks!

**Pull request merged**
