### PR TITLE
add highlighter #1773

### PR DESCRIPTION
**Pull request by ifowiyu123**

### CODE REVIEW

**Comment by birkenfeld** [comment]
This looks like just a simpler version of pygmentize/python -m pygments?

**Comment by ifowiyu123** [comment]
> This looks like just a simpler version of pygmentize/python -m pygments?

It could be. I would say it’s a more user-friendly version.

**Comment by Jean-Abou-Samra** [comment]
Hi, could you explain how this script differs from the current CLI and why it is appropriate for it to be separate?

**Comment by birkenfeld** [comment]
Closing in the current form. If there are some simplifications you'd like in pygmentize, please integrate it there (maybe with new options), and we can discuss from there.

**Pull request closed without merging**
