### PR TITLE
advance development of typst lexer

### PR DESCRIPTION
**Pull request by jonaspleyer**
This PR adds multiple improvements to the existing typst lexer and some tests
- One of these tests is currently failing. This is by design.

I cannot guarantee that I will be working on this problem too much but wanted to get these commits out here.
Please tell me if the failing test prohibits merging. I can comment it out such that future development can reference it.

Happy about any feedback.

### CODE REVIEW

**Comment by jonaspleyer** [comment]
> I'm not sure if you saw, but the Typst test file which was previously introduced is invalid, see [#2596 (comment)](https://github.com/pygments/pygments/pull/2596#issuecomment-1858957697) (or that is what you meant by failing by design idk)

I did not see the original typst file to be honest. I added my own tests which are much more specific and only parse individual snippets. See commit https://github.com/pygments/pygments/pull/2656/commits/93e9eeab3d3e8215849e7d80c350e0fe37771815. There one of the tests is failing. Of course, this is due to the lexer not picking it up correctly. Think of it as TDD ;-)  where the correct implementation is still missing.

**Review by jeanas — CHANGES_REQUESTED** [review]
Sorry for the delayed review. Please do the testing via our normal infrastructure with a file in `tests/snippets/typst/`, not with extra Python code, see https://pygments.org/docs/lexerdevelopment/#how-to-test-your-lexer.

**Comment by Nerixyz** [comment]
Hi, since this wasn't updated in a while, I did some work on it.

- I refactored the tests from `test_typst.py` into snippets in https://github.com/Nerixyz/pygments/commit/c229ee79bb1b2060da599b72ab486c5fe13d699e (as mentioned in https://github.com/pygments/pygments/pull/2656#pullrequestreview-1968361647)
- The current example code isn't valid Typst, so I fixed it in https://github.com/Nerixyz/pygments/commit/37077faa5577d49f7763ea4bdd48406b749a79d8 (this can't be compiled, but that's because `darkgrey` and `section_date` don't exist which the lexer shouldn't have to care about)
- Code can't contain text, so I moved the text to `markup` (you can't have raw links in code for example), moved the literal case introduced in this PR down, and introduced a case for variables in https://github.com/Nerixyz/pygments/commit/8e301d3091cc07e1e3710d9a556f6bfa8bcdcac9
- Inline code was broken on linebreaks - fixed in https://github.com/Nerixyz/pygments/commit/c1d6691dcc361c3b086601336d59370dabf7cc85
- Typst has the convention to use kebab-case and `-` wasn't supported in variables and function names - fixed in https://github.com/Nerixyz/pygments/commit/342f65fda7ce3c891a708c5d1f364fe2c044c9c3
- `#{` was treated as inline code, which meant it would pop back to markup after a linebreak - fixed in https://github.com/Nerixyz/pygments/commit/22304656ec2751b86c372b99525ff2a30a68987d
- Special characters like `---` or `\` weren't recognized, because they used the `\b` suffix - fixed in https://github.com/Nerixyz/pygments/commit/5746cbeb454aedd9fc292c89ee5e03b93c69549c
- The text regex in markup would capture too much - most importantly, it would capture functions - fixed in https://github.com/Nerixyz/pygments/commit/06dc2f0123002353a9e5a8c1872684f902fd93b7
- To ensure nesting of `#{ }` code works correctly, I added another snippet in https://github.com/Nerixyz/pygments/commit/9fb2abafe0bcb874b6d2e35ef9e66adc4692b8d0
- Finally, I added support for `#import` and `#include` in https://github.com/Nerixyz/pygments/commit/1c9fd95e25ff7cfe7c57b3c6f4026e4895265740

All commits: https://github.com/Nerixyz/pygments/commits/fix/typst-advance/
Full diff to current state: https://github.com/Nerixyz/pygments/compare/93e9eeab3d3e8215849e7d80c350e0fe37771815...1c9fd95e25ff7cfe7c57b3c6f4026e4895265740

@jonaspleyer let me know if I should PR the fixes to your branch or if I should open another PR here.

**Comment by jonaspleyer** [comment]
> Hi, since this wasn't updated in a while, I did some work on it.
> 
>     * I refactored the tests from `test_typst.py` into snippets in [Nerixyz@c229ee7](https://github.com/Nerixyz/pygments/commit/c229ee79bb1b2060da599b72ab486c5fe13d699e) (as mentioned in [advance development of typst lexer #2656 (review)](https://github.com/pygments/pygments/pull/2656#pullrequestreview-1968361647))
> 
>     * The current example code isn't valid Typst, so I fixed it in [Nerixyz@37077fa](https://github.com/Nerixyz/pygments/commit/37077faa5577d49f7763ea4bdd48406b749a79d8) (this can't be compiled, but that's because `darkgrey` and `section_date` don't exist which the lexer shouldn't have to care about)
> 
>     * Code can't contain text, so I moved the text to `markup` (you can't have raw links in code for example), moved the literal case introduced in this PR down, and introduced a case for variables in [Nerixyz@8e301d3](https://github.com/Nerixyz/pygments/commit/8e301d3091cc07e1e3710d9a556f6bfa8bcdcac9)
> 
>     * Inline code was broken on linebreaks - fixed in [Nerixyz@c1d6691](https://github.com/Nerixyz/pygments/commit/c1d6691dcc361c3b086601336d59370dabf7cc85)
> 
>     * Typst has the convention to use kebab-case and `-` wasn't supported in variables and function names - fixed in [Nerixyz@342f65f](https://github.com/Nerixyz/pygments/commit/342f65fda7ce3c891a708c5d1f364fe2c044c9c3)
> 
>     * `#{` was treated as inline code, which meant it would pop back to markup after a linebreak - fixed in [Nerixyz@2230465](https://github.com/Nerixyz/pygments/commit/22304656ec2751b86c372b99525ff2a30a68987d)
> 
>     * Special characters like `---` or `\` weren't recognized, because they used the `\b` suffix - fixed in [Nerixyz@5746cbe](https://github.com/Nerixyz/pygments/commit/5746cbeb454aedd9fc292c89ee5e03b93c69549c)
> 
>     * The text regex in markup would capture too much - most importantly, it would capture functions - fixed in [Nerixyz@06dc2f0](https://github.com/Nerixyz/pygments/commit/06dc2f0123002353a9e5a8c1872684f902fd93b7)
> 
>     * To ensure nesting of `#{ }` code works correctly, I added another snippet in [Nerixyz@9fb2aba](https://github.com/Nerixyz/pygments/commit/9fb2abafe0bcb874b6d2e35ef9e66adc4692b8d0)
> 
>     * Finally, I added support for `#import` and `#include` in [Nerixyz@1c9fd95](https://github.com/Nerixyz/pygments/commit/1c9fd95e25ff7cfe7c57b3c6f4026e4895265740)
> 
> 
> All commits: https://github.com/Nerixyz/pygments/commits/fix/typst-advance/ Full diff to current state: [Nerixyz/pygments@93e9eea...1c9fd95](https://github.com/Nerixyz/pygments/compare/93e9eeab3d3e8215849e7d80c350e0fe37771815...1c9fd95e25ff7cfe7c57b3c6f4026e4895265740)
> 
> @jonaspleyer let me know if I should PR the fixes to your branch or if I should open another PR here.

To be honest I had kind of forgotten about this PR until today. I have had a brief glance on the individual commits (without too much depth) and they seem reasonable to me.

I currently do not have the time to further contribute to this PR. Thus it would make  sense to open a new one instead. Feel free to tag me once you have done so. Afterwards I will close this PR.
I am only concerned about my contributions showing up correctly but I see that you have simply pulled my repository and committed on top. This should probably be enough.

Thanks for your effort.

**Comment by jonaspleyer** [comment]
closing in favor of #2724

**Pull request closed without merging**
