### PR TITLE
Don't require script headers in Rebol and Red codes.

### PR DESCRIPTION
**Pull request by Oldes**
Resolves: https://github.com/pygments/pygments/issues/2348

### CODE REVIEW

**Comment by birkenfeld** [comment]
The header should still be highlighted in some way if present I suppose?

**Comment by Oldes** [comment]
@birkenfeld unfortunately as there is no way to find out if the code is a complete script or just a snipped of it, the header may not be highlighted how it was. Because one could have such an input:
```rebol
switch language [
    Rebol [ print "bla" ]
    Perl  [ print "foo" ]
]
```
But as the header is just an ordinary Rebol data, it will be highlighted too... the only difference is, that what is before header in a complete script will not be handled like a comment.

**Comment by birkenfeld** [comment]
OK, makes sense. Just one nit: please remove the unneeded code instead of commenting.

**Comment by Oldes** [comment]
@birkenfeld the code is removed now.

**Comment by birkenfeld** [comment]
Thanks!

**Pull request merged**
