### PR TITLE
Added cartouche handling for Isabelle lexer

### LINKED ISSUE #1905: WIP - Whitespace lexing after Keywords - collecting issue
In a recent PR, it become apparent, that there are a lot of places where the whitespace following a Keyword has been often implemented as the `Text` token. Instead the more specific `Text.Whitespace` token is more applicable here.

This issue shall serve as reference and log for similar issues/PRs.

Since initial tests showed a large number of lexers which can be updated, a more systematic approach is tried with the table below. The table lists all lexers in pygments, the status of work, and related issues and PRs. The status shows whether a quick check shows a need for change, whether Whitespace token are already used (hence nothing needs to be done in these cases), or whether the lexers still needs to be inspected whether there is this issue.

## State of the cleanup

| Lexer | Status | PRs and issues |
| --- | --- | --- |
| actionscript | :heavy_check_mark: merged |  #1911 |
| agile | :white_check_mark: nothing to do| |
| algebra | :white_check_mark: nothing to do| |
| ambient | :heavy_check_mark: merged  | #1914 |
| amdgpu | :white_check_mark: nothing to do| |
| ampl | :heavy_check_mark: merged  | #1914 |
| apdlexer | :heavy_check_mark: merged  | #1914 |
| apl | :heavy_check_mark: merged  | #1914 |
| archetype | :heavy_check_mark: merged  | #1914 |
| arrow | :heavy_check_mark: merged  | #1914 |
| asc | :white_check_mark: nothing to do| |
| asm | :heavy_check_mark: merged  | #1914 |
| automation | :triangular_flag_on_post: more elaborate change necessary  |  |
| bare | :heavy_check_mark: merged |  #1911 |
| basic |  :heavy_check_mark: merged  | #1923|
| bibtex |   :heavy_check_mark: merged | #1923|
| boa |  :heavy_check_mark: merged  | #1923|
| business | :heavy_check_mark: merged :curly_loop: needs refactor  | #1911 |
| capnproto |  :heavy_check_mark: merged  | #1923|
| c_cpp | :heavy_check_mark: merged |   #1237(#1904) |
| cddl |  :heavy_check_mark: merged  | #1923|
| chapel | :heavy_check_mark: merged  | #1923|
| clean | :white_check_mark: nothing to do| |
| c_like |  :heavy_check_mark: merged  | #1923|
| compiled | :white_check_mark: nothing to do| |
| configs |  :heavy_check_mark: merged  | #1923|
| console | :heavy_check_mark: merged  | #1923|
| crystal |  :heavy_check_mark: merged  | #1923|
| csound |  :heavy_check_mark: merged  | #1923|
| css | :heavy_check_mark: merged  | #1923|
| dalvik |  :heavy_check_mark: merged | #1939 |
| data |  :heavy_check_mark: merged | #1939 |
| devicetree | :heavy_check_mark: merged | #1939 |
| diff | :heavy_check_mark: merged | #1939,  #1911 |
| dotnet |  :heavy_check_mark: merged | #1939 |
| d | :heavy_check_mark: merged | #1939 |
| dsls |  :heavy_check_mark: merged | #1939 |
| dylan |  :heavy_check_mark: merged | #1939 |
| ecl |  :heavy_check_mark: merged  | #1957 |
| eiffel | :heavy_check_mark: merged  | #1957 |
| elm |  :heavy_check_mark: merged  | #1957 |
| email | :white_check_mark: nothing to do| |
| erlang |  :heavy_check_mark: merged  | #1957 |
| esoteric | :heavy_check_mark: merged  | #1957 |
| ezhil | :heavy_check_mark: merged  | #1957 |
| factor | :heavy_check_mark: merged  | #1957 |
| fantom | :heavy_check_mark: merged  | #1957 |
| felix | :heavy_check_mark: merged  | #1957 |
| floscript | :heavy_check_mark: merged  | #1957 |
| forth | :heavy_check_mark: merged  | #1957 |
| fortran |  :white_check_mark: nothing to do| |
| foxpro | :triangular_flag_on_post: needs change, major refactor for reserved Keywords | |
| freefem |  :white_check_mark: nothing to do| |
| functional |  :white_check_mark: nothing to do| |
| futhark |  :heavy_check_mark: merged  | #1957 |
| gcodelexer | :white_check_mark: nothing to do| |
| gdscript |  :heavy_check_mark: merged  | #1978|
| go |   :heavy_check_mark: merged  | #1978|
| grammar_notation |   :heavy_check_mark: merged :triangular_flag_on_post: needs refactor (multiline comment, floats,...) | #1978| |
| graphics |  :heavy_check_mark: merged  | #1978|
| graph |   :heavy_check_mark: merged  | #1978|
| graphviz |  :white_check_mark: nothing to do| |
| gsql.py | :white_check_mark: nothing to do| |
| haskell |  :heavy_check_mark: merged  | #1978|
| haxe |   :heavy_check_mark: merged  | #1978|
| hdl |  :heavy_check_mark: merged  | #1978|
| hexdump |  :heavy_check_mark: merged  | #1978|
| html |  :curly_loop: in review | #2012 |
| idl |   :curly_loop: in review | #2025 |
| igor |  :curly_loop: in review | #2025 |
| inferno |  :curly_loop: in review | #2025 |
| installers |  :curly_loop: in review | #2025 |
| int_fiction |  :curly_loop: in review | #2025 |
| iolang |  :curly_loop: in review | #2025 |
| javascript | :curly_loop: in review | #2025 |
| j |  :curly_loop: in review | #2025 |
| jslt |:white_check_mark: nothing to do| |
| julia |  :curly_loop: in review | #2025 |
| jvm |  :curly_loop: in review | #2025 |
| kuin |  :curly_loop: in review | #2025 |
| lisp |  :curly_loop: in review | #2025 |
| make | :heavy_check_mark: merged , :triangular_flag_on_post: needs more change, missed some spaces |  #1911 |
| markup | :triangular_flag_on_post: needs change | |
| math | :white_check_mark: nothing to do| |
| matlab | :triangular_flag_on_post: needs change | |
| maxima | :white_check_mark: nothing to do| |
| meson | :white_check_mark: nothing to do| |
| mime | :grey_question: looks good, but check again later | |
| ml | :triangular_flag_on_post: needs change | |
| modeling | :triangular_flag_on_post: needs change | |
| modula2 | :triangular_flag_on_post: needs change | |
| monte | :white_check_mark: nothing to do| |
| mosel | :triangular_flag_on_post: needs change | |
| ncl | :triangular_flag_on_post: needs change | |
| nimrod |:triangular_flag_on_post: needs change | |
| nit | :triangular_flag_on_post: needs change | |
| nix |:triangular_flag_on_post: needs change | |
| oberon |:triangular_flag_on_post: needs change | |
| objective | :triangular_flag_on_post: needs change | |
| ooc | :triangular_flag_on_post: needs change | |
| other | :white_check_mark: nothing to do| |
| parasail | :triangular_flag_on_post: needs change | |
| parsers | :triangular_flag_on_post: needs change | |
| pascal |:triangular_flag_on_post: needs change | |
| pawn |:triangular_flag_on_post: needs change | |
| perl | :triangular_flag_on_post: needs change | |
| php | :triangular_flag_on_post: needs change | |
| pointless | :triangular_flag_on_post: needs change | |
| pony | :triangular_flag_on_post: needs change | |
| praat |:triangular_flag_on_post: needs change | |
| procfile | :white_check_mark: nothing to do| |
| prolog | :triangular_flag_on_post: needs change | |
| promql | :white_check_mark: nothing to do| |
| python | :triangular_flag_on_post: needs change | |
| qvt | :triangular_flag_on_post: needs change | |
| rdf | :triangular_flag_on_post: needs change | |
| rebol | :triangular_flag_on_post: needs change | |
| resource | :triangular_flag_on_post: needs change | |
| ride | :triangular_flag_on_post: needs change | |
| rnc | :triangular_flag_on_post: needs change | |
| roboconf | :triangular_flag_on_post: needs change | |
| robotframework | :triangular_flag_on_post: needs change, seems more work | |
| r | :triangular_flag_on_post: needs change | |
| ruby | :triangular_flag_on_post: needs change | |
| rust | :triangular_flag_on_post: needs change | |
| sas | :triangular_flag_on_post: needs change | |
| scdoc | :triangular_flag_on_post: needs change | |
| scripting | :triangular_flag_on_post: needs change | |
| sgf | :white_check_mark: nothing to do| |
| shell |  :triangular_flag_on_post: needs change | |
| sieve |  :triangular_flag_on_post: needs change | |
| slash |  :white_check_mark: nothing to do| |
| smalltalk | :triangular_flag_on_post: needs change | |
| smithy | :triangular_flag_on_post: needs change | |
| smv | :white_check_mark: nothing to do| |
| snobol | :triangular_flag_on_post: needs change | |
| solidity | :white_check_mark: nothing to do| |
| special |:white_check_mark: nothing to do| |
| sql | :heavy_check_mark: merged, :triangular_flag_on_post: needs more change | #1908 |
| srcinfo | :white_check_mark: nothing to do| |
| stata | :triangular_flag_on_post: needs change | |
| supercollider | :triangular_flag_on_post: needs change | |
| tcl | :triangular_flag_on_post: needs change | |
| teal | :triangular_flag_on_post: needs change | |
| templates | :triangular_flag_on_post: needs change | |
| teraterm | :triangular_flag_on_post: needs change | |
| testing | :triangular_flag_on_post: needs change | |
| textedit | :triangular_flag_on_post: needs change | |
| textfmts | :triangular_flag_on_post: needs change | |
| text | :white_check_mark: nothing to do| |
| theorem | :triangular_flag_on_post: needs change | |
| thingsdb | :triangular_flag_on_post: needs change | |
| tnt | :triangular_flag_on_post: needs change | |
| trafficscript | :triangular_flag_on_post: needs change | |
| typoscript | :triangular_flag_on_post: needs change | |
| unicon | :triangular_flag_on_post: needs change | |
| urbi | :triangular_flag_on_post: needs change | |
| usd | :white_check_mark: nothing to do| |
| varnish |  :triangular_flag_on_post: needs change | |
| verification |  :triangular_flag_on_post: needs change | |
| webassembly |  :triangular_flag_on_post: needs change | |
| webidl | :triangular_flag_on_post: needs change | |
| webmisc | :triangular_flag_on_post: needs change | |
| web |  :white_check_mark: nothing to do| |
| whiley | :triangular_flag_on_post: needs change | |
| x10 | :triangular_flag_on_post: needs change | |
| xorg | :triangular_flag_on_post: needs change | |
| yang | :white_check_mark: nothing to do| |
| zig |  :white_check_mark: nothing to do| |

### PR DESCRIPTION
**Pull request by Dacit**
In Isabelle, cartouches are nowadays widely used. However, they can not be parsed by the Isabelle lexer so lots of unparsed tokens are left over - this PR adds better support for them, as well as symbol names in their unicode representation.

Also fixes #1905 for Isabelle.

### CODE REVIEW

**Comment by Jean-Abou-Samra** [comment]
Could you add a test? Either modify the existing `tests/examplefiles/isabelle/example.thy`, or add `tests/snippets/isabelle/cartouches.txt`. In either case, run `pytest --update-goldens tests/<examplefiles or snippets>/isabelle` to update golden test output.

**Comment by Jean-Abou-Samra** [comment]
Ping @Dacit, do you need help?

**Comment by Dacit** [comment]
> Ping @Dacit, do you need help?

Thanks for the offer, I was just very busy and couldn't get to that until now. I'll add tests for that, and even a bit more functionality.

**Comment by Dacit** [comment]
@Jean-Abou-Samra added the tests, now separately for the ascii sources and their unicode rendering (the latter is often used in code snippets, whereas the former is how Isabelle sources are stored).

**Review by Jean-Abou-Samra — APPROVED** [review]
Thanks!

**Pull request merged**
