### PR TITLE
TNTLexer: Don't crash on unexpected EOL.

### LINKED ISSUE #1568: TNTLexer crashes with input '0'
While working on #1425 I used Hypothesis to help me identify JSON lexing issues.

Hypothesis immediately reported a crash bug in the TNT lexer. It crashes with an IndexError if you pass `0` as the input string:

```
>>> import pygments.lexers
>>> list(pygments.lexers.TNTLexer().get_tokens('0'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Kurt\Documents\dev\pygments\pygments\lexer.py", line 188, in streamer
    for _, t, v in self.get_tokens_unprocessed(text):
  File "C:\Users\Kurt\Documents\dev\pygments\pygments\lexers\tnt.py", line 215, in get_tokens_unprocessed
    start = end = self.formula(start, text)
  File "C:\Users\Kurt\Documents\dev\pygments\pygments\lexers\tnt.py", line 107, in formula
    if text[start] in '[]':  # fantasy push or pop
IndexError: string index out of range
```

### PR DESCRIPTION
**Pull request by Kenny2github**
Closes #1568 which is blocking #1425

### CODE REVIEW

**Comment by Kenny2github** [comment]
Force pushed to just the one commit (the others are already in the repo)

**Comment by Anteru** [comment]
Could you please add a test case for this?

**Review by Anteru — CHANGES_REQUESTED** [review]
Please add a test case for this (it should crash without the change applied.)

**Comment by Kenny2github** [comment]
(Seen 4 hours ago, been writing tests for the whole lexer ever since)

**Comment by Anteru** [comment]
That looks fairly comprehensive, thanks! I'll wait for the tests to finish, then merge -- thanks for your contribution.

**Pull request merged**
