### PR TITLE
1526/fusumwan/unreadablestyle

### PR DESCRIPTION
**Pull request by a1714470**
Creating a way to check if a style defines all colors and if those have good contrast. The "check.py" is used to fixed issue 

https://github.com/pygments/pygments/issues/1526

In general, our check.py includes a color similarity function. Such a function is used to list out all the color similarities from one style. Besides, the check function also includes the contrast rato, relative luminance, contrast AA, and contrast AAA. We hope it can check all styles.

### CODE REVIEW

**Comment by Anteru** [comment]
Thanks for preparing this. I've got a few comments:

* First, please separate out the style update itself from this change. They're not directly related and if I had to undo one of them, ths would take the other with it.
* There's no helper script to actually run the checks. It would be good to add one and hook it up to `make check`.
* There are styles with low contrast ratio, so the script should warn if a style is below the W3 recommendation.
* The checker itself has no tests. It would be helpful to test it somehow -- though that might be not needed once there is an automated way to check styles.

**Comment by a1714470** [comment]
Thanks for your advice, we will pick that up one month later.

**Comment by Anteru** [comment]
I don't know what happened here. Did someone hack your account? There's a ton of unrelated files which makes this PR unacceptable.

**Comment by a1714470** [comment]
> I don't know what happened here. Did someone hack your account? There's a ton of unrelated files which makes this PR unacceptable.

Actually, Leo777i and Hannah40 are my team members. Because they didn't want to do programming tasks, so they uploaded a lot of irrelevant documents to prove their work this semester. As our lecturer needs to review our jobs, so I cannot delete their files. I warned them not to upload these irrelevant files before. But they didn't accept my advice. My team has five members. However, I am the only one dedicated to solving this issue. Sorry, I stopped updating this task now. I will report to our lecturer first.

Sorry for all the inconvenience.

**Comment by Anteru** [comment]
Ok. That's rather sad to hear. Thanks for clearing this up! Any chance you can open a new PR with just the `check.py` and I'll happily approve it; without all the other files/changes which are irrelevant to the problem at hand?

**Comment by a1714470** [comment]
> Ok. That's rather sad to hear. Thanks for clearing this up! Any chance you can open a new PR with just the `check.py` and I'll happily approve it; without all the other files/changes which are irrelevant to the problem at hand?

Thank you for your advice, I need to seek advice from my lecturer first. Then maybe I just delete their files or open a new PR.

**Comment by a1714470** [comment]
HI, after discussing with my lecturer, I will open a new PR. Thanks for your advice.

**Pull request closed without merging**
