### PR TITLE
Support Terraform 0.14 syntax

### PR DESCRIPTION
**Pull request by lgiordani**
This is my second attempt to write a Pygments lexer, and the first one didn't go very well, so apologies in advance if I misused part of the API.

This has been tested against my whole code base which is more than 100k lines of TF code. Even though it doesn't span the whole syntax and resources i thing it's a good test. I cannot publish it, though, so I went for smaller tests that highlight the issues I had.

Let me know if you think that is enough.

### CODE REVIEW

**Comment by lgiordani** [comment]
I'm not actually sure what `W119: Instead of negating character class, flip case of builtin class` means in the regexlint output. Any help?

**Comment by birkenfeld** [comment]
Ah yes - the builtin classes like `\s`, `\w` have opposites `\S`, `\W`.

**Comment by lgiordani** [comment]
Oh! That simple :sweat_smile: Thanks, I'm going to fix it

**Comment by lgiordani** [comment]
@Anteru Thanks for merging it!

**Pull request merged**
