### PR TITLE
Revert "Add Lexer for NVIDIA PTX"

### PR DESCRIPTION
**Pull request by Matt711**
Reverts pygments/pygments#2432

### CODE REVIEW

**Comment by Anteru** [comment]
What is going on here? Technically the contribution has been done already; and wouldn't it make more sense to wait before you remove it again instead of removing it "for now"? Is there anything we can do to help keep the PR?

**Comment by gmarkall** [comment]
(I am working with @Matt711)

@Anteru Apologies for the confusion here - the original PRs were submitted prior to open-source contribution approval due to a miscommunication - this was an attempt to remedy that situation. I think (if it's OK for you) let's pause on this PR, and then if any further changes are requested for the open-source contribution approval, we'll modify this PR accordingly and ask you to review them (hopefully we're not asked to make changes and can just eventually close this PR). Does this sound OK?

**Comment by Anteru** [comment]
Sounds good. I hope you can sort it out on your end, I don't see how this should cause any legal trouble but then again IANAL :) Do you have an ETA how long this will take? I'd like to make a release end of Q2, you think you'll have this cleared by then?

**Comment by gmarkall** [comment]
I'm hoping it will just be a few days, it normally doesn't take long for this sort of thing - I'm not expecting any trouble :-)

**Comment by gmarkall** [comment]
Just for clarity and to close the loop, the open-source contribution was approved, so the NVIDIA PTX lexer that was already merged required can remain merged.

**Pull request closed without merging**
