### PR TITLE
Add NestedText lexer

### PR DESCRIPTION
**Pull request by kalekundert**
This PR adds a lexer for NestedText, a pretty simple markup language.  This is my first time contributing to pygments, so I'm happy to get any feedback.

### CODE REVIEW

**Comment by kalekundert** [comment]
Any update on this PR?  I'd like to get it merged if possible.

**Comment by Anteru** [comment]
Sorry for not getting to this earlier. We've changed to a new test system in the meantime, could you please update this PR accordingly and then I think it's good to merge?

**Comment by kalekundert** [comment]
Ok, I think the tests are updated.  Really I just renamed the test file and ran `pytest --update-goldens nt/test.nt`, but I think that's all I need to do.  Let me know if there's anything I missed.

**Comment by Anteru** [comment]
Merged, thanks for the contribution!

**Pull request merged**
